apiVersion: v1
kind: ConfigMap
metadata:
  name: easyshop-config
  namespace: tws-e-commerce-app
data:
  NODE_ENV: "production"
  PORT: "3000"
  NEXTAUTH_URL: "http://51.44.219.238:30080"
  NEXT_PUBLIC_API_URL: "http://51.44.219.238:30080/api"
