# Prod overrides for nha-monitoring
kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 30d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: gp3
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 100Gi
  grafana:
    persistence:
      size: 20Gi

loki:
  loki:
    storage:
      bucketNames:
        chunks: easyshop-prod-logs-bucket
        ruler: easyshop-prod-logs-bucket
        admin: easyshop-prod-logs-bucket
